on:
  pull_request:
    types: [closed]

name: Merged PR SonarQube Push
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: load
      run: npm ci
    - name: temp load jest
      run: npm i -g jest@28.1.3
    - name: temp report create
      run:  jest --collectCoverageFrom='["**/*.{js,jsx}", "!**/node_modules/**", "!**/coverage/**", "!jest.config.js"]' --coverage --collectCoverage=true
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
