on: [pull_request]

name: Merged PR SonarQube Push
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Merge pull request') }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: load
      run: npm ci
    - name: temp load jest
      run: npm i -g jest@28.1.3
    - name: TestCoverage
      id: testCoverage
      uses: anuraag016/Jest-Coverage-Diff@master
      with:
        fullCoverageDiff: false
        runCommand: "npx jest --collectCoverageFrom='[\"**/*.{js,jsx}\", \"!**/node_modules/**\", \"!**/coverage/**\", \"!jest.config.js\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary'"
        delta: 0.5
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        useSameComment: true
