on: [push, pull_request]
  

jobs:
  build:
    if: ${{ github.event.pull_request.head.sha }}
    # Name the Job
    name: Coverage Commenting
    # Set the agent to run on
  
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Load all steps #    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm i -g jest@28.1.3
      - run: npm i -D jest-junit
      - run: npm run test
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-final.json
          title: Coverage Report 
          summary-title: Only For Changed Files
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: Coverage
          junitxml-path: ./junit.xml

