on:
  pull_request:
    types:
      - closed

name: Merged PR SonarQube Push
jobs:
  sonarqube:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm ci
    - run: npm i -g jest@28.1.3
    - run: npm i -D jest-junit
    - run: npm run test-actions
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./coverage/coverage-final.json
        title: Coverage Report 
        summary-title: Only For Changed Files
        badge-title: Coverage
        hide-comment: false
        create-new-comment: true
        hide-summary: false
        junitxml-title: Coverage
        junitxml-path: ./junit.xml
        coverage-title: My Coverage Title
        coverage-path: ./coverage-report.txt
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
