on:
  pull_request:
    types:
      - closed

name: Merged PR SonarQube Push
jobs:
  sonarqube:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* # fetches all branches
        git checkout -b master # -b creates and checks out a new branch
        git checkout ${{ github.event.pull_request.head.sha }} # checks out the SHA of the HEAD from the PR
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm ci
    - run: mkdir coverage
    - run: jest --config=./jest.config.js --coverage --changedSince=origin/main | tee ./coverage/coverage-report.txt
    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./coverage/coverage-final.json
        title: Coverage Report 
        summary-title: All Files
        badge-title: Coverage
        hide-comment: false
        create-new-comment: true
        hide-summary: false
        junitxml-title: Coverage
        junitxml-path: ./coverage/junit.xml
        coverage-title: My Coverage Title
        coverage-path: ./coverage/coverage-report.txt
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
