on: [push, pull_request]
  

jobs:
  build:
    if: ${{ github.event.pull_request.head.sha }}
    # Name the Job
    name: Coverage Commenting
    # Set the agent to run on
  
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Load all steps #    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch --no-tags --depth=1 origin main
          git checkout -b main origin/main
          git checkout ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: mkdir coverage
      - run: jest --coverage --changedSince=origin/main | tee ./coverage-report.txt
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-final.json
          title: Coverage Report 
          summary-title: Only For Changed Files
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: Coverage
          junitxml-path: ./junit.xml
          coverage-title: My Coverage Title
          coverage-path: ./coverage-report.txt

